[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "celery>=5.6.3",
    "fastapi>=0.110.0",
    "faster-whisper",
    "httpx>=0.28.1",
    "pyannote.audio",
    "pydantic",
    "pytest>=9.1.1",
    "pytest-mock>=3.15.1",
    "python-multipart",
    "redis>=8.0.1",
    "scikit-learn>=1.7.2",
    "sqlalchemy",
    "torch",
    "torchaudio",
    "torchvision",
    "uvicorn[standard]",
]

[tool.uv.sources]
torch = { index = "pytorch" }
torchaudio = { index = "pytorch" }
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu121"
explicit = true
